# Generated by Django 4.1.4 on 2024-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
