# Generated by Django 4.1.4 on 2024-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
