# Generated by Django 4.2.7 on 2024-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
