# Generated by Django 5.1.1 on 2024-09-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_delete_events'),
        ('payments', '0004_transaction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='project',
        ),
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
