# Generated by Django 5.1.1 on 2024-09-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
