# Generated by Django 5.1.1 on 2024-09-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_price_alter_events_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
