# Generated by Django 5.1.1 on 2024-09-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_delete_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
