# Generated by Django 4.1.4 on 2024-09-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sno',
            new_name='id',
        ),
    ]
