# Generated by Django 5.1.1 on 2024-09-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_thumbnail_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
